project_name: redix
builds:
  - id: redix
    main: ./server/cmd/redix-server
    binary: redix-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
      - -X main.commit={{.ShortCommit}}
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - src: configs/config.yml
        dst: .
        strip_parent: true
