version: 2.1

orbs:
  docker: circleci/docker@2.0.2

jobs:
  test:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Run unit tests
          command: make test
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  lint:
    docker:
      - image: golangci/golangci-lint:v1.44.2-alpine
    steps:
      - checkout
      - run: golangci-lint run

workflows:
  main:
    jobs:
      - test
      - lint
      - docker/publish:
          requires:
            - test
            - lint
          extra_build_args: "--build-arg BRANCH=${CIRCLE_BRANCH} --build-arg COMMIT=${CIRCLE_SHA1:0:7}"
          image: maolonglong/redix
          tag: latest
          filters:
            branches:
              only: main
