version: 2.1

orbs:
  docker: circleci/docker@2.0.2

jobs:
  test:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: make test
  lint:
    docker:
      - image: golangci/golangci-lint:v1.44.2-alpine
    steps:
      - checkout
      - run:
          name: Run lint
          command: golangci-lint run
  release:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  untagged-build:
    jobs:
      - test
      - lint
  tagged-build:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - lint:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - docker/publish:
          requires:
            - test
            - lint
          extra_build_args: "--build-arg COMMIT=${CIRCLE_SHA1:0:7}"
          image: maolonglong/redix
          tag: "latest,${CIRCLE_TAG:1}"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release:
          requires:
            - test
            - lint
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
